/* automatically generated by rust-bindgen 0.69.5 */

pub const MEM_F_PE: u32 = 2;
pub const MEM_F_NOPAIRING: u32 = 4;
pub const MEM_F_ALL: u32 = 8;
pub const MEM_F_NO_MULTI: u32 = 16;
pub const MEM_F_NO_RESCUE: u32 = 32;
pub const MEM_F_REF_HDR: u32 = 256;
pub const MEM_F_SOFTCLIP: u32 = 512;
pub const MEM_F_SMARTPE: u32 = 1024;
pub const MEM_F_PRIMARY5: u32 = 2048;
pub const MEM_F_KEEP_SUPP_MAPQ: u32 = 4096;
pub const MEM_F_XB: u32 = 8192;
pub const BWA_ORIGIN_PAIR: u32 = 0;
pub const BWA_ORIGIN_SINGLE: u32 = 1;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mem_opt_t {
    pub a: ::std::os::raw::c_int,
    pub b: ::std::os::raw::c_int,
    pub o_del: ::std::os::raw::c_int,
    pub e_del: ::std::os::raw::c_int,
    pub o_ins: ::std::os::raw::c_int,
    pub e_ins: ::std::os::raw::c_int,
    pub pen_unpaired: ::std::os::raw::c_int,
    pub pen_clip5: ::std::os::raw::c_int,
    pub pen_clip3: ::std::os::raw::c_int,
    pub w: ::std::os::raw::c_int,
    pub zdrop: ::std::os::raw::c_int,
    pub max_mem_intv: u64,
    pub T: ::std::os::raw::c_int,
    pub flag: ::std::os::raw::c_int,
    pub min_seed_len: ::std::os::raw::c_int,
    pub min_ext_len: ::std::os::raw::c_int,
    pub max_extend_chains: ::std::os::raw::c_int,
    pub mate_concordant_window: ::std::os::raw::c_int,
    pub est_insert_high: ::std::os::raw::c_int,
    pub extend_tie_frac: f32,
    pub extend_csub: ::std::os::raw::c_int,
    pub extend_tie_floor: ::std::os::raw::c_int,
    pub seed_emit_order: ::std::os::raw::c_int,
    pub min_chain_weight: ::std::os::raw::c_int,
    pub max_chain_extend: ::std::os::raw::c_int,
    pub split_factor: f32,
    pub split_width: ::std::os::raw::c_int,
    pub max_occ: ::std::os::raw::c_int,
    pub max_chain_gap: ::std::os::raw::c_int,
    pub n_threads: ::std::os::raw::c_int,
    pub chunk_size: i64,
    pub mask_level: f32,
    pub drop_ratio: f32,
    pub XA_drop_ratio: f32,
    pub mask_level_redun: f32,
    pub mapQ_coef_len: f32,
    pub mapQ_coef_fac: ::std::os::raw::c_int,
    pub max_ins: ::std::os::raw::c_int,
    pub max_matesw: ::std::os::raw::c_int,
    pub rescue_kmer: ::std::os::raw::c_int,
    pub rescue_band: ::std::os::raw::c_int,
    pub rescue_skip: ::std::os::raw::c_int,
    pub max_XA_hits: ::std::os::raw::c_int,
    pub max_XA_hits_alt: ::std::os::raw::c_int,
    pub mat: [i8; 25usize],
    pub mat_ot: [i8; 25usize],
    pub mat_ob: [i8; 25usize],
    pub bam_mode: ::std::os::raw::c_int,
    pub bam_level: ::std::os::raw::c_int,
    pub bam_threads: ::std::os::raw::c_int,
    pub meth_mode: ::std::os::raw::c_int,
    pub meth_scoring: ::std::os::raw::c_int,
    pub meth_seed_prune: ::std::os::raw::c_int,
    pub meth_chem: ::std::os::raw::c_int,
    pub meth_tags: ::std::os::raw::c_int,
    pub meth_set_as_failed: ::std::os::raw::c_char,
    pub meth_chimera_qc: ::std::os::raw::c_int,
    pub proper_pair_from_emitted: ::std::os::raw::c_int,
    pub supp_rep_hard_cap: ::std::os::raw::c_int,
    pub smem_dedup: ::std::os::raw::c_int,
    pub alnreg_sort_fast: ::std::os::raw::c_int,
    pub skip_contained_ext: ::std::os::raw::c_int,
    pub band_start: ::std::os::raw::c_int,
    pub band_cert: ::std::os::raw::c_int,
    pub compat: *const ::std::os::raw::c_void,
}
#[test]
fn bindgen_test_layout_mem_opt_t() {
    const UNINIT: ::std::mem::MaybeUninit<mem_opt_t> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<mem_opt_t>(),
        344usize,
        concat!("Size of: ", stringify!(mem_opt_t))
    );
    assert_eq!(
        ::std::mem::align_of::<mem_opt_t>(),
        8usize,
        concat!("Alignment of ", stringify!(mem_opt_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).a) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(a)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).b) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(b)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).o_del) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(o_del)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).e_del) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(e_del)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).o_ins) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(o_ins)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).e_ins) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(e_ins)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).pen_unpaired) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(pen_unpaired)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).pen_clip5) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(pen_clip5)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).pen_clip3) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(pen_clip3)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).w) as usize - ptr as usize },
        36usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(w)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).zdrop) as usize - ptr as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(zdrop)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).max_mem_intv) as usize - ptr as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(max_mem_intv)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).T) as usize - ptr as usize },
        56usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(T)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).flag) as usize - ptr as usize },
        60usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(flag)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).min_seed_len) as usize - ptr as usize },
        64usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(min_seed_len)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).min_ext_len) as usize - ptr as usize },
        68usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(min_ext_len)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).max_extend_chains) as usize - ptr as usize },
        72usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(max_extend_chains)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).mate_concordant_window) as usize - ptr as usize },
        76usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(mate_concordant_window)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).est_insert_high) as usize - ptr as usize },
        80usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(est_insert_high)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).extend_tie_frac) as usize - ptr as usize },
        84usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(extend_tie_frac)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).extend_csub) as usize - ptr as usize },
        88usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(extend_csub)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).extend_tie_floor) as usize - ptr as usize },
        92usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(extend_tie_floor)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).seed_emit_order) as usize - ptr as usize },
        96usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(seed_emit_order)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).min_chain_weight) as usize - ptr as usize },
        100usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(min_chain_weight)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).max_chain_extend) as usize - ptr as usize },
        104usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(max_chain_extend)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).split_factor) as usize - ptr as usize },
        108usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(split_factor)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).split_width) as usize - ptr as usize },
        112usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(split_width)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).max_occ) as usize - ptr as usize },
        116usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(max_occ)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).max_chain_gap) as usize - ptr as usize },
        120usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(max_chain_gap)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).n_threads) as usize - ptr as usize },
        124usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(n_threads)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).chunk_size) as usize - ptr as usize },
        128usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(chunk_size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).mask_level) as usize - ptr as usize },
        136usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(mask_level)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).drop_ratio) as usize - ptr as usize },
        140usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(drop_ratio)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).XA_drop_ratio) as usize - ptr as usize },
        144usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(XA_drop_ratio)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).mask_level_redun) as usize - ptr as usize },
        148usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(mask_level_redun)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).mapQ_coef_len) as usize - ptr as usize },
        152usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(mapQ_coef_len)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).mapQ_coef_fac) as usize - ptr as usize },
        156usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(mapQ_coef_fac)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).max_ins) as usize - ptr as usize },
        160usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(max_ins)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).max_matesw) as usize - ptr as usize },
        164usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(max_matesw)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).rescue_kmer) as usize - ptr as usize },
        168usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(rescue_kmer)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).rescue_band) as usize - ptr as usize },
        172usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(rescue_band)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).rescue_skip) as usize - ptr as usize },
        176usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(rescue_skip)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).max_XA_hits) as usize - ptr as usize },
        180usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(max_XA_hits)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).max_XA_hits_alt) as usize - ptr as usize },
        184usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(max_XA_hits_alt)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).mat) as usize - ptr as usize },
        188usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(mat)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).mat_ot) as usize - ptr as usize },
        213usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(mat_ot)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).mat_ob) as usize - ptr as usize },
        238usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(mat_ob)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).bam_mode) as usize - ptr as usize },
        264usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(bam_mode)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).bam_level) as usize - ptr as usize },
        268usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(bam_level)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).bam_threads) as usize - ptr as usize },
        272usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(bam_threads)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).meth_mode) as usize - ptr as usize },
        276usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(meth_mode)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).meth_scoring) as usize - ptr as usize },
        280usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(meth_scoring)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).meth_seed_prune) as usize - ptr as usize },
        284usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(meth_seed_prune)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).meth_chem) as usize - ptr as usize },
        288usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(meth_chem)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).meth_tags) as usize - ptr as usize },
        292usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(meth_tags)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).meth_set_as_failed) as usize - ptr as usize },
        296usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(meth_set_as_failed)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).meth_chimera_qc) as usize - ptr as usize },
        300usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(meth_chimera_qc)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).proper_pair_from_emitted) as usize - ptr as usize },
        304usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(proper_pair_from_emitted)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).supp_rep_hard_cap) as usize - ptr as usize },
        308usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(supp_rep_hard_cap)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).smem_dedup) as usize - ptr as usize },
        312usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(smem_dedup)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).alnreg_sort_fast) as usize - ptr as usize },
        316usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(alnreg_sort_fast)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).skip_contained_ext) as usize - ptr as usize },
        320usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(skip_contained_ext)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).band_start) as usize - ptr as usize },
        324usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(band_start)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).band_cert) as usize - ptr as usize },
        328usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(band_cert)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).compat) as usize - ptr as usize },
        336usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_opt_t),
            "::",
            stringify!(compat)
        )
    );
}
impl Default for mem_opt_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct mem_pestat_t {
    pub low: ::std::os::raw::c_int,
    pub high: ::std::os::raw::c_int,
    pub failed: ::std::os::raw::c_int,
    pub avg: f64,
    pub std: f64,
}
#[test]
fn bindgen_test_layout_mem_pestat_t() {
    const UNINIT: ::std::mem::MaybeUninit<mem_pestat_t> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<mem_pestat_t>(),
        32usize,
        concat!("Size of: ", stringify!(mem_pestat_t))
    );
    assert_eq!(
        ::std::mem::align_of::<mem_pestat_t>(),
        8usize,
        concat!("Alignment of ", stringify!(mem_pestat_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).low) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_pestat_t),
            "::",
            stringify!(low)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).high) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_pestat_t),
            "::",
            stringify!(high)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).failed) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_pestat_t),
            "::",
            stringify!(failed)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).avg) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_pestat_t),
            "::",
            stringify!(avg)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).std) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(mem_pestat_t),
            "::",
            stringify!(std)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct BwaAlignedFields {
    pub tid: i32,
    pub pos: i32,
    pub next_tid: i32,
    pub next_pos: i32,
    pub tlen: i32,
    pub flag: u16,
    pub bin: u16,
    pub mapq: u8,
    pub query_start: i32,
    pub query_end: i32,
    pub cigar: *const u32,
    pub n_cigar: u32,
    pub has_nm: u8,
    pub nm: i32,
    pub md: *const ::std::os::raw::c_char,
    pub mc: *const ::std::os::raw::c_char,
    pub has_mq: u8,
    pub mq: i32,
    pub has_as: u8,
    pub score: i32,
    pub has_xs: u8,
    pub sub: i32,
    pub rg: *const ::std::os::raw::c_char,
    pub sa: *const ::std::os::raw::c_char,
    pub has_pa: u8,
    pub pa: f32,
    pub xa: *const ::std::os::raw::c_char,
    pub has_hn: u8,
    pub hn: i32,
    pub xr: *const ::std::os::raw::c_char,
    pub xg: *const ::std::os::raw::c_char,
    pub xm: *const ::std::os::raw::c_char,
}
#[test]
fn bindgen_test_layout_BwaAlignedFields() {
    const UNINIT: ::std::mem::MaybeUninit<BwaAlignedFields> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<BwaAlignedFields>(),
        168usize,
        concat!("Size of: ", stringify!(BwaAlignedFields))
    );
    assert_eq!(
        ::std::mem::align_of::<BwaAlignedFields>(),
        8usize,
        concat!("Alignment of ", stringify!(BwaAlignedFields))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).tid) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(tid)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).pos) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(pos)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).next_tid) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(next_tid)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).next_pos) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(next_pos)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).tlen) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(tlen)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).flag) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(flag)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).bin) as usize - ptr as usize },
        22usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(bin)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).mapq) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(mapq)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).query_start) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(query_start)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).query_end) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(query_end)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).cigar) as usize - ptr as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(cigar)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).n_cigar) as usize - ptr as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(n_cigar)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).has_nm) as usize - ptr as usize },
        52usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(has_nm)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).nm) as usize - ptr as usize },
        56usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(nm)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).md) as usize - ptr as usize },
        64usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(md)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).mc) as usize - ptr as usize },
        72usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(mc)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).has_mq) as usize - ptr as usize },
        80usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(has_mq)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).mq) as usize - ptr as usize },
        84usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(mq)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).has_as) as usize - ptr as usize },
        88usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(has_as)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).score) as usize - ptr as usize },
        92usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(score)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).has_xs) as usize - ptr as usize },
        96usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(has_xs)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).sub) as usize - ptr as usize },
        100usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(sub)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).rg) as usize - ptr as usize },
        104usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(rg)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).sa) as usize - ptr as usize },
        112usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(sa)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).has_pa) as usize - ptr as usize },
        120usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(has_pa)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).pa) as usize - ptr as usize },
        124usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(pa)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).xa) as usize - ptr as usize },
        128usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(xa)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).has_hn) as usize - ptr as usize },
        136usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(has_hn)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).hn) as usize - ptr as usize },
        140usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(hn)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).xr) as usize - ptr as usize },
        144usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(xr)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).xg) as usize - ptr as usize },
        152usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(xg)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).xm) as usize - ptr as usize },
        160usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaAlignedFields),
            "::",
            stringify!(xm)
        )
    );
}
impl Default for BwaAlignedFields {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type BwaFieldSinkFn = ::std::option::Option<
    unsafe extern "C" fn(
        ctx: *mut ::std::os::raw::c_void,
        origin_kind: u32,
        origin_idx: usize,
        mate: u8,
        is_primary: ::std::os::raw::c_int,
        f: *const BwaAlignedFields,
    ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct BwaIndex {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct BwaSeeds {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct BwaBatch {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct BwaScratch {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct BwaRegs {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct BwaResidentCohort {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct BwaResidentSegment {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct BwaReadPair {
    pub r1_name: *const ::std::os::raw::c_char,
    pub r1_name_len: usize,
    pub r1_seq: *const u8,
    pub r1_seq_len: usize,
    pub r1_qual: *const u8,
    pub r2_name: *const ::std::os::raw::c_char,
    pub r2_name_len: usize,
    pub r2_seq: *const u8,
    pub r2_seq_len: usize,
    pub r2_qual: *const u8,
}
#[test]
fn bindgen_test_layout_BwaReadPair() {
    const UNINIT: ::std::mem::MaybeUninit<BwaReadPair> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<BwaReadPair>(),
        80usize,
        concat!("Size of: ", stringify!(BwaReadPair))
    );
    assert_eq!(
        ::std::mem::align_of::<BwaReadPair>(),
        8usize,
        concat!("Alignment of ", stringify!(BwaReadPair))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).r1_name) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaReadPair),
            "::",
            stringify!(r1_name)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).r1_name_len) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaReadPair),
            "::",
            stringify!(r1_name_len)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).r1_seq) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaReadPair),
            "::",
            stringify!(r1_seq)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).r1_seq_len) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaReadPair),
            "::",
            stringify!(r1_seq_len)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).r1_qual) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaReadPair),
            "::",
            stringify!(r1_qual)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).r2_name) as usize - ptr as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaReadPair),
            "::",
            stringify!(r2_name)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).r2_name_len) as usize - ptr as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaReadPair),
            "::",
            stringify!(r2_name_len)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).r2_seq) as usize - ptr as usize },
        56usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaReadPair),
            "::",
            stringify!(r2_seq)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).r2_seq_len) as usize - ptr as usize },
        64usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaReadPair),
            "::",
            stringify!(r2_seq_len)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).r2_qual) as usize - ptr as usize },
        72usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaReadPair),
            "::",
            stringify!(r2_qual)
        )
    );
}
impl Default for BwaReadPair {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct BwaSingleRead {
    pub name: *const ::std::os::raw::c_char,
    pub name_len: usize,
    pub seq: *const u8,
    pub seq_len: usize,
    pub qual: *const u8,
}
#[test]
fn bindgen_test_layout_BwaSingleRead() {
    const UNINIT: ::std::mem::MaybeUninit<BwaSingleRead> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<BwaSingleRead>(),
        40usize,
        concat!("Size of: ", stringify!(BwaSingleRead))
    );
    assert_eq!(
        ::std::mem::align_of::<BwaSingleRead>(),
        8usize,
        concat!("Alignment of ", stringify!(BwaSingleRead))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).name) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaSingleRead),
            "::",
            stringify!(name)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).name_len) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaSingleRead),
            "::",
            stringify!(name_len)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).seq) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaSingleRead),
            "::",
            stringify!(seq)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).seq_len) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaSingleRead),
            "::",
            stringify!(seq_len)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).qual) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaSingleRead),
            "::",
            stringify!(qual)
        )
    );
}
impl Default for BwaSingleRead {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct BwaReadBatch {
    pub pairs: *const BwaReadPair,
    pub n_pairs: usize,
    pub singles: *const BwaSingleRead,
    pub n_singles: usize,
}
#[test]
fn bindgen_test_layout_BwaReadBatch() {
    const UNINIT: ::std::mem::MaybeUninit<BwaReadBatch> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<BwaReadBatch>(),
        32usize,
        concat!("Size of: ", stringify!(BwaReadBatch))
    );
    assert_eq!(
        ::std::mem::align_of::<BwaReadBatch>(),
        8usize,
        concat!("Alignment of ", stringify!(BwaReadBatch))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).pairs) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaReadBatch),
            "::",
            stringify!(pairs)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).n_pairs) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaReadBatch),
            "::",
            stringify!(n_pairs)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).singles) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaReadBatch),
            "::",
            stringify!(singles)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).n_singles) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaReadBatch),
            "::",
            stringify!(n_singles)
        )
    );
}
impl Default for BwaReadBatch {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
extern "C" {
    pub fn bwa_shim_opts_new() -> *mut mem_opt_t;
}
extern "C" {
    pub fn bwa_shim_opts_free(opts: *mut mem_opt_t);
}
extern "C" {
    pub fn bwa_shim_opts_fill_meth_mat(opts: *mut mem_opt_t);
}
extern "C" {
    pub fn bwa_shim_opts_fill_scmat(opts: *mut mem_opt_t);
}
extern "C" {
    pub fn bwa_shim_opts_set_int(
        opts: *mut mem_opt_t,
        key: *const ::std::os::raw::c_char,
        value: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn bwa_shim_compat_hd_line(opts: *const mem_opt_t) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn bwa_shim_opts_apply_meth_defaults(opts: *mut mem_opt_t);
}
extern "C" {
    pub fn bwa_shim_pestat_zero() -> *mut mem_pestat_t;
}
extern "C" {
    pub fn bwa_shim_pestat_free(pestat: *mut mem_pestat_t);
}
extern "C" {
    pub fn bwa_shim_idx_load(prefix: *const ::std::os::raw::c_char) -> *mut BwaIndex;
}
extern "C" {
    pub fn bwa_shim_idx_load_threads(
        prefix: *const ::std::os::raw::c_char,
        n_threads: ::std::os::raw::c_int,
    ) -> *mut BwaIndex;
}
extern "C" {
    pub fn bwa_shim_idx_load_meth(
        seed_prefix: *const ::std::os::raw::c_char,
        orig_prefix: *const ::std::os::raw::c_char,
    ) -> *mut BwaIndex;
}
extern "C" {
    pub fn bwa_shim_idx_is_meth(idx: *const BwaIndex) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn bwa_shim_idx_free(idx: *mut BwaIndex);
}
extern "C" {
    pub fn bwa_shim_idx_n_contigs(idx: *const BwaIndex) -> usize;
}
extern "C" {
    pub fn bwa_shim_idx_contig_name(
        idx: *const BwaIndex,
        i: usize,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn bwa_shim_idx_contig_len(idx: *const BwaIndex, i: usize) -> i64;
}
extern "C" {
    pub fn bwa_shim_seed_batch(
        idx: *const BwaIndex,
        opts: *const mem_opt_t,
        pairs: *const BwaReadPair,
        n_pairs: usize,
    ) -> *mut BwaSeeds;
}
extern "C" {
    pub fn bwa_shim_seeds_free(seeds: *mut BwaSeeds);
}
extern "C" {
    pub fn bwa_shim_extend_batch(
        idx: *const BwaIndex,
        opts: *const mem_opt_t,
        seeds: *mut BwaSeeds,
        pairs: *const BwaReadPair,
        n_pairs: usize,
        pestat_in: *const mem_pestat_t,
        pestat_out: *mut mem_pestat_t,
    ) -> *mut BwaBatch;
}
extern "C" {
    pub fn bwa_shim_align_batch(
        idx: *const BwaIndex,
        opts: *const mem_opt_t,
        pairs: *const BwaReadPair,
        n_pairs: usize,
        pestat_in: *const mem_pestat_t,
        pestat_out: *mut mem_pestat_t,
    ) -> *mut BwaBatch;
}
extern "C" {
    pub fn bwa_shim_estimate_pestat(
        idx: *const BwaIndex,
        opts: *const mem_opt_t,
        pairs: *const BwaReadPair,
        n_pairs: usize,
        pestat_out: *mut mem_pestat_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn bwa_shim_scratch_new() -> *mut BwaScratch;
}
extern "C" {
    pub fn bwa_shim_scratch_free(sc: *mut BwaScratch);
}
extern "C" {
    pub fn bwa_shim_seed_extend(
        idx: *const BwaIndex,
        opts: *const mem_opt_t,
        sc: *mut BwaScratch,
        batch: *const BwaReadBatch,
    ) -> *mut BwaRegs;
}
extern "C" {
    pub fn bwa_shim_regs_free(r: *mut BwaRegs);
}
extern "C" {
    pub fn bwa_shim_regs_n_pairs(r: *const BwaRegs) -> usize;
}
extern "C" {
    pub fn bwa_shim_regs_n_singles(r: *const BwaRegs) -> usize;
}
extern "C" {
    pub fn bwa_shim_regs_heap_bytes(r: *const BwaRegs) -> usize;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct BwaIdBases {
    pub first_single_id: u64,
    pub first_pair_id: u64,
}
#[test]
fn bindgen_test_layout_BwaIdBases() {
    const UNINIT: ::std::mem::MaybeUninit<BwaIdBases> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<BwaIdBases>(),
        16usize,
        concat!("Size of: ", stringify!(BwaIdBases))
    );
    assert_eq!(
        ::std::mem::align_of::<BwaIdBases>(),
        8usize,
        concat!("Alignment of ", stringify!(BwaIdBases))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).first_single_id) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaIdBases),
            "::",
            stringify!(first_single_id)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).first_pair_id) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(BwaIdBases),
            "::",
            stringify!(first_pair_id)
        )
    );
}
pub type BwaRecordSinkFn = ::std::option::Option<
    unsafe extern "C" fn(
        ctx: *mut ::std::os::raw::c_void,
        origin_kind: u32,
        origin_idx: usize,
        body: *const u8,
        body_len: usize,
    ),
>;
extern "C" {
    pub fn bwa_shim_pestat_cohort(
        idx: *const BwaIndex,
        opts: *const mem_opt_t,
        regs: *const *const BwaRegs,
        n_regs: usize,
        out: *mut mem_pestat_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn bwa_shim_pair_emit(
        idx: *const BwaIndex,
        opts: *const mem_opt_t,
        sc: *mut BwaScratch,
        regs: *mut BwaRegs,
        pestat: *const mem_pestat_t,
        ids: BwaIdBases,
        sink: BwaRecordSinkFn,
        ctx: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn bwa_shim_resident_cohort_new(meth_mode: ::std::os::raw::c_int)
        -> *mut BwaResidentCohort;
}
extern "C" {
    pub fn bwa_shim_resident_cohort_free(c: *mut BwaResidentCohort);
}
extern "C" {
    pub fn bwa_shim_resident_read_overhead() -> usize;
}
extern "C" {
    pub fn bwa_shim_resident_reserve_pairs(
        c: *mut BwaResidentCohort,
        n_reads: usize,
        first_out: *mut usize,
    ) -> *mut BwaResidentSegment;
}
extern "C" {
    pub fn bwa_shim_resident_reserve_singles(
        c: *mut BwaResidentCohort,
        n_reads: usize,
        first_out: *mut usize,
    ) -> *mut BwaResidentSegment;
}
extern "C" {
    pub fn bwa_shim_resident_write_pair(
        sg: *mut BwaResidentSegment,
        i: usize,
        pair: *const BwaReadPair,
        added: *mut usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn bwa_shim_resident_write_single(
        sg: *mut BwaResidentSegment,
        i: usize,
        single: *const BwaSingleRead,
        added: *mut usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn bwa_shim_resident_write_pairs(
        sg: *mut BwaResidentSegment,
        pairs: *const BwaReadPair,
        n: usize,
        added: *mut usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn bwa_shim_resident_write_singles(
        sg: *mut BwaResidentSegment,
        reads: *const BwaSingleRead,
        n: usize,
        added: *mut usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn bwa_shim_resident_seed_extend(
        idx: *const BwaIndex,
        opts: *const mem_opt_t,
        sc: *mut BwaScratch,
        sg: *mut BwaResidentSegment,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn bwa_shim_resident_pestat_cohort(
        idx: *const BwaIndex,
        opts: *const mem_opt_t,
        c: *const BwaResidentCohort,
        out: *mut mem_pestat_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn bwa_shim_resident_pair_emit(
        idx: *const BwaIndex,
        opts: *const mem_opt_t,
        sc: *mut BwaScratch,
        sg: *mut BwaResidentSegment,
        pestat: *const mem_pestat_t,
        ids: BwaIdBases,
        origin_base: usize,
        sink: BwaRecordSinkFn,
        ctx: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn bwa_shim_resident_pair_emit_fields(
        idx: *const BwaIndex,
        opts: *const mem_opt_t,
        sc: *mut BwaScratch,
        sg: *mut BwaResidentSegment,
        pestat: *const mem_pestat_t,
        ids: BwaIdBases,
        origin_base: usize,
        sink: BwaFieldSinkFn,
        ctx: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn bwa_shim_batch_n_records(b: *const BwaBatch) -> usize;
}
extern "C" {
    pub fn bwa_shim_batch_pair_idx(b: *const BwaBatch, rec: usize) -> usize;
}
extern "C" {
    pub fn bwa_shim_batch_record_ptr(b: *const BwaBatch, rec: usize) -> *const u8;
}
extern "C" {
    pub fn bwa_shim_batch_record_len(b: *const BwaBatch, rec: usize) -> usize;
}
extern "C" {
    pub fn bwa_shim_batch_free(b: *mut BwaBatch);
}
extern "C" {
    pub fn bwa_shim_last_error() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn bwa_shim_set_verbosity(level: ::std::os::raw::c_int);
}
extern "C" {
    pub fn bwa_shim_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn bwa_shim_build_info() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn bwa_shim_shm_test(prefix: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn bwa_shim_shm_stage(prefix: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn bwa_shim_shm_destroy() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn bwa_shim_shm_list() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn bwa_shim_set_rg_id(id: *const ::std::os::raw::c_char);
}
